### PR TITLE
feat: add load_vyi and loads_vyi

### PR DESCRIPTION
**Pull request by charles-cooper**
create an ABIContractFactory from a vyi file

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by AlbertoCentonze** [comment]
Nice, why not allow load_partial to load from `.vyi` files instead of creating a new function?

**Comment by DanielSchiavini** [comment]
`boa.loads(interface_code, is_interface=True)` would be nice but not consistent with `boa.loads_abi(abi)`

**Comment by charles-cooper** [comment]
> Nice, why not allow `load_partial` to load from `.vyi` files instead of creating a new function?

requires some guessing to figure out if it's an interface or not, and as daniel pointed out it's consistent with load_abi

**Review by DanielSchiavini — APPROVED** [review]

**Comment by DanielSchiavini** [comment]
This looks fine but it is still a different interface then https://github.com/vyperlang/titanoboa/pull/260
@bout3fiddy does this cover your use cases?

**Pull request merged**
